name: lionax-wedding
services:
- environment_slug: python
  envs:
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "True"
  - key: DJANGO_ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: ${APP_DOMAIN}
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE_URL}
  - key: DEVELOPMENT_MODE
    scope: RUN_AND_BUILD_TIME
    value: "True"
  github:
    branch: main
    deploy_on_push: true
    repo: TonyEight/lionax-wedding
  http_port: 8008
  instance_count: 1
  instance_size_slug: basic-xs
  name: lionax-wedding
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm lionax_wedding.wsgi
  source_dir: /
jobs:
- name: makemigrations
  kind: PRE_DEPLOY
  github:
    repo: TonyEight/lionax-wedding
    branch: main
    deploy_on_push: true
  run_command: python manage.py makemigrations
  envs:
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
    scope: RUN_AND_BUILD_TIME
- name: migrate
  kind: PRE_DEPLOY
  github:
    repo: TonyEight/lionax-wedding
    branch: main
    deploy_on_push: true
  run_command: python manage.py migrate
  envs:
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
    scope: RUN_AND_BUILD_TIME
static_sites:
- name: static
  github:
    repo: TonyEight/lionax-wedding
    branch: main
    deploy_on_push: true
  # This happens as part of the Python/DJango buildpack:
  # build_command: python manage.py collectstatic --noinput
  output_dir: staticfiles
  routes:
  - path: /static
databases:
# Create a new dev DB:
- name: db
  engine: PG
  version: "12"
# Or bring an existing DB:
# - name: db
#   production: true
#   cluster_name: mydb
#   engine: PG
#   version: "12"
