name: lionax-wedding
region: fra
services:
- environment_slug: python
  envs:
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "True"
  - key: DJANGO_ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: ${APP_DOMAIN}
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE_URL}
  - key: DEVELOPMENT_MODE
    scope: RUN_AND_BUILD_TIME
    value: "False"
  github:
    branch: main
    deploy_on_push: true
    repo: TonyEight/lionax-wedding
  http_port: 8008
  instance_count: 1
  instance_size_slug: basic-xs
  name: lionax-wedding
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm lionax_wedding.wsgi
  source_dir: /
static_sites:
- name: static
  github:
    repo: TonyEight/lionax-wedding
    branch: main
    deploy_on_push: true
  output_dir: staticfiles
  routes:
  - path: /static
databases:
- cluster_name: app-501b3aef-db75-4633-a1ae-03632ddb1df4
  db_name: db
  db_user: db
  engine: PG
  name: db
  production: true
  version: "12"
domains:
- domain: mariage.axelleetludovic.fr
  type: PRIMARY