# Generated by Django 3.1.6 on 2021-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile_phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_the_ceremony', models.BooleanField()),
                ('attend_the_dinner', models.BooleanField()),
                ('attend_the_party', models.BooleanField()),
                ('sleep_at_domain', models.BooleanField()),
                ('attend_the_brunch', models.BooleanField()),
                ('is_eligible_to_sunday', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('hidden_comment', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(related_name='invitations', to='attendees.Attendee')),
            ],
        ),
    ]
