# Generated by Django 3.1.6 on 2021-07-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_auto_20210706_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='accept_to_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='attend_the_brunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sleep_at_domain',
            field=models.BooleanField(default=False),
        ),
    ]
