# Generated by Django 3.1.6 on 2021-07-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_auto_20210709_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='last_editor',
            field=models.CharField(blank=True, default='Axelle et Ludovic', max_length=255),
        ),
    ]
