# Generated by Django 3.1.6 on 2021-07-11 21:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0005_auto_20210711_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
