# Generated by Django 3.1.6 on 2021-07-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0006_auto_20210711_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
