# Generated by Django 3.1.6 on 2021-07-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0007_auto_20210711_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='attend_the_ceremony',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='attend_the_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='attend_the_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='hidden_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
